### ISSUE TITLE
Kml format color

### ISSUE THREAD

**Issue by pokomoko** [shramov/leaflet-plugins#109]
Hi, 
How can I change the color for several KML? I tried with extractStyles: true, extractAttributes:true, but it doesn't work!
<head>
    <title>Leaflet</title>
    <meta charset="utf-8" />
    <meta content="width=device-width,initial-scale=1.0" name="viewport" />
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7/leaflet.css" />
    <link rel="stylesheet" type="text/css" href="L.Control.Locate.css">
    <script src="http://cdn.leafletjs.com/leaflet-0.7/leaflet.js"></script>
    <script src="L.Control.Locate.js"></script>
    <script src="KML.js"></script>
</head>
<body>
    <div style="width:100%; height:100%" id="map"></div>

<script type='text/javascript'>
var map = new L.Map('map', {center: new L.LatLng(41.5988, 1.8089), zoom: 14});
var osmAttrib='Map data © OpenStreetMap contributors';
var osm = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {attribution: osmAttrib});

var track = new L.KML("KML_Samples.kml", {async: false});
track.on("loaded", function(e) { map.fitBounds(e.target.getBounds()); });

var canals = new L.KML("canals.kml", {extractStyles: true, extractAttributes: true});
track.on("loaded", function(e) { map.fitBounds(e.target.getBounds()); });

map.addLayer(track);
map.addLayer(canals);
map.addLayer(osm);
map.addControl(new L.Control.Layers({}, {'Track':track, 'Canals':canals}));

var lc = L.control.locate({
    follow: true
}).addTo(map);
lc.locate();
</script>
 

KML - Styler
<kml xmlns="http://earth.google.com/kml/2.0"><Folder><name>Vissir3 export</name><description>Exported on 19/6/2013 9:08:30</description><Placemark><name>Les Canals</name><description></description><LineString><Style><LineStyle><color>ffa90230</color></LineStyle></Style><coordinates>1.8379492957477892,41.607907051769295 1.8379186320662384,41.60787701847696 1.8379406340508666,41.60785472324645 1.8379322005834844,41.60782311327278 1.8379174848668591,41.60780720214762 1.8379148084009655,41.60778916096561 1.8379241307707692,........

**Comment by JLuc** [comment]
FYI, on a related issue, Klaus says : « Syntax for `<LineString>` of the KML is
```
        <Style>
          <LineStyle>
            <color>7f0000ff</color>
          </LineStyle>
        </Style>

```
