### ISSUE TITLE
Google : laggy panning

### ISSUE THREAD

**Issue by SeBsZ** [shramov/leaflet-plugins#111]
I'm adding markers in real-time every few seconds to leaflet. When viewing using OpenStreetMap tiles, it pans nicely to the new marker. When using Shramov's Google plugin there is a strange lag/flicker when the map pans to the new marker.

It's hard to explain. The markers are close together, only a few 100meters apart. This "bug" is observed in IE11 and Chrome.

This image shows the moment of panning. The fact that tiles are missing is not a huge problem for me, but the panning animation is very laggy. Even existing markers and polylines move "stuttering".

![mapbug](https://f.cloud.github.com/assets/5457531/2216873/87fd2154-9a12-11e3-937b-d67d1c98d593.png)

Hopefully I managed to be clear in explaining the issue. Thanks!

**Comment by TheSisb** [comment]
Apparently it's fine to use Leaflet if you have a Maps for Work license.

**Comment by frankydp** [comment]
I can confirm that use with leaflet while under a Maps for Work license was allowed, after directly requesting confirmation of this use case from our account manager.

**Comment by rvanbaalen** [comment]
Thats nice and all but there are free alternatives that perform just as good without the need of fancy licenses.

I could just use the Google Maps API for a map implementation instead of using Leaflet + Maps for Work license, right?

**Comment by frankydp** [comment]
The issue is the implementation while building a paid product.  All of the big providers except Bing explicitly disallow that use, including MapQuest.

**Comment by rvanbaalen** [comment]
So when I have for instance a paid app that uses Leaflet, that's not allowed? Even when I give full credit in lets say an 'about' page or so?

**Comment by TheSisb** [comment]
It's unfortunate that Leaflet doesn't really work that well with Google map tiles (panning and zooming lags and seems a little off).
The reason why I would prefer to use Leaflet is because the Google Maps V3 API is rather rigid and has but a handful of plugins to use.  Leaflet on the other hand has a full community behind it, which means a much nicer library to use for development and many plugins that can really help speed up development.

**Comment by frankydp** [comment]
Attribution guidelines are extremely specific.  Most require attribution be displayed on map at a minimum.  Furthermore, most attribution is secondary meaning Google is adhering to someone elses attribution requirements, and that is why they are so specific about how people use their maps. 

As for using google maps, or any provider, without a formal licensing agreement, that is very grey, and unless there are specifically allowed app based terms it is without a doubt violating TOS.

**Comment by rvanbaalen** [comment]
I dont know if you're using Angular @TheSisb but if you do you could give `angular-google-maps` a try. It's very extensive with loads of addons and features.

**Comment by TheSisb** [comment]
I hadn't seen that.  It looks like a step in the right direction (for Google Maps) but we don't currently use Angular on our project.  If the decision is made to use Google Maps over an alternative at this point, I'll may include Angular in our project just for the map.  Seems like overkill though.

**Comment by rvanbaalen** [comment]
As you confirmed yourself; that seems like an extremely unwise choice. Using a full framework just to use a plugin for that framework is indeed a huge overkill.

Don't know if you're familiar with PHP but it's like installing all of Symphony just to send an e-mail. Or including jQuery just to change the contents of a span once.

Like I said; overkill. Choose wisely which framework / library / plugin to use and why.

**Comment by brunob** [comment]
Closing this old issue since nobody is working on it. Feel free to provide a pull req for that :)

**Comment by rcknr** [comment]
@brunob I've tried to get around this and used several techniques to make it smoother but the best it got is like this https://jsfiddle.net/rcknr/jqyjup8g/ i.e. just slightly less horrible than it is right now.
Do you want me to pull request this?

**Comment by brunob** [comment]
@rcknr yes a PR would be nice and more easy to see the diff :)

**Comment by r1g0** [comment]
Changing this line 

`this._limitedUpdate = L.Util.limitExecByInterval(this._update, 150, this);`

to

`this._limitedUpdate = L.Util.limitExecByInterval(this._update, 0, this);`

really improved it for me.
