### ISSUE TITLE
Google Reset

### ISSUE THREAD

**Issue by rntdrts** [shramov/leaflet-plugins#119]
I think this feature ain't working right. i looked at some examples from google maps and they pointed out to the same solution that's been doing here... in other/developer words: 		

google.maps.event.trigger(this._google, "resize");

i don't know if it's because of the association between google maps and leaflet architecture of the plugin, or if it's a problem from google. I work the thing around using the method onRemove and the method OnAdd (it's tricky, i know). 

Also in the method OnRemove it can work with only one type, but it doesn't work with many, the _container variable fixes the id with the last one used, and on the removeChild it doesn't work if you select a previous type. So i also work it around:

this._map._container.removeChild(this._map._container.childNodes[0]);
(it always remove the _container in the map.)

PS: Don't know if i'm writing in the right place.. 

thanks for your atention. Best regards.

**Comment by brunob** [comment]
The script you are using seems different than the one we provide in this repo, you should provide a fiddle using the right version of google script.

What are you exactly trying to do ?

**Comment by rntdrts** [comment]
I don't really recall what i was doing here (it was for my last job). But has the example show, there's basic functionalities that don't do what it was expected to do. As the google script code, i think it was extracted from here, a year ago(i think).

**Comment by brunob** [comment]
Ok, so i think we can close this issue (feel free to open a new one with updated code if you still get this bug).
