### ISSUE TITLE
L.DeferredLayer doesn't work in IE8

### ISSUE THREAD

**Issue by fiskus** [shramov/leaflet-plugins#136]
IE8 doesn't support `onload` for <script> tags.
http://stackoverflow.com/questions/4845762/onload-handler-for-script-tag-in-internet-explorer

**Comment by brunob** [comment]
Since IE8 is not supported anymore i think we can close this issue (http://fr.wikipedia.org/wiki/Internet_Explorer#Internet_Explorer_8).
