### ISSUE TITLE
Bing Map Layer

### ISSUE THREAD

**Issue by smitchell** [shramov/leaflet-plugins#148]
I'm playing with the Bing and Google plugins on my demo site, http://www.exploringspatial.com/#demo4. The Google and OSM map layers work fine; however, the Bing map layer is blank. 

The map set-up happens here:

https://github.com/smitchell/exploringspatial/blob/master/js/views/demos/demo4/Demo4RightSideView.js

The provider is changed here:

https://github.com/smitchell/exploringspatial/blob/master/js/views/demos/demo4/MapProviderControlsView.js

The map provider control removes other map layers before adding a new layer. When I tried removing Bing (commented out now) I got an undefined reference in Bing.js because this._providers was not there:

```javascript
	onRemove: function(map) {
		for (var i = 0; i < this._providers.length; i++) {
```
Does anybody see any obvious errors?

**Comment by brunob** [comment]
Cool, can close this one easily :)
