### ISSUE TITLE
Bing layer issue

### ISSUE THREAD

**Issue by steerdavies** [shramov/leaflet-plugins#154]
After implementing all the necessary files from the plugin into my code, I try to add the Bing layers but I get the following error:

Uncaught typeerror: cannot read property '_leaflet_id' of null

Any ideas? Any help would be much appreciated.

**Comment by brunob** [comment]
Hi, hard to help without a fiddle or a demo page that show the bug.

**Comment by antoinegiret** [comment]
Hi, I have the same problem ! For information I use the cdn http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js

```
var bing = L.BingLayer('...');
console.log(bing)
```

Variable bing is undefined !

**Comment by brunob** [comment]
as usual, hard to help without a fiddle or a demo page that show the bug...

**Comment by brunob** [comment]
No news since a month, closing it but feel free to open if needed :)
