### ISSUE TITLE
KML icons enhancement

### ISSUE THREAD

**Issue by brunob** [shramov/leaflet-plugins#159]
Work is on in kml_icon branch.

- [x] Icon hotSpot xunits and yunits can be different 1292beec4e1e61f8d5635205cb80de569bed9fbb
- [x] fix popup anchor when hotSpot is defined 6deca8dc6aead5b72810ef0ab22c2fbaf6dd5288
- [ ] <del>Handle icons scale</del>
- [ ] <del>Fix default icons position and scale</del>

Links for refs : 

https://github.com/openlayers/ol3/commit/65fe82d1889c508679cf88f140b6f0071e209c5d

https://github.com/openlayers/openlayers/blob/master/lib/OpenLayers/Format/KML.js#L437

scale : https://github.com/bshelton229/Leaflet.photomarker/blob/master/src/PhotoIcon.js#L45

KML Elements Supported in Google Maps : https://developers.google.com/kml/documentation/kmlelementsinmaps

https://code.google.com/p/geoxml3/source/browse/branches/network_link/geoxml3.js#405

**Comment by kalenkov** [comment]
leaflet KML ignores xunits and yunits if they defined in pixels. Please look at the simple example below

http://katrine.lpi.ru/kalenkov/leaflet/hotspot-kml.html
http://katrine.lpi.ru/kalenkov/leaflet/hotspot.kml

I expect that the placemark icons should be shifted by 100 pixels in x and 100 pixels in y directions, But instead they completely overlap.

**Comment by brunob** [comment]
@kalenkov could you test with the https://github.com/shramov/leaflet-plugins/tree/kml_icon please ?

**Comment by kalenkov** [comment]
yes, kml_icon branch works fine
http://katrine.lpi.ru/kalenkov/leaflet/hotspot-kml_icon.html

**Comment by brunob** [comment]
Great, thx for the feedback, just have to wait this branch merge.
