### ISSUE TITLE
leaflet-control-attribution class

### ISSUE THREAD

**Issue by jblarsen** [shramov/leaflet-plugins#160]
Hi,

In some cases I hide the Leaflet attributions (when using homemade maps). But since Permalink objects also have the leaflet-control-attribution class that is hidden as well:

https://github.com/shramov/leaflet-plugins/blob/master/control/Permalink.js

'''this._container = L.DomUtil.create('div', 'leaflet-control-attribution leaflet-control-permalink');'''

Is the leaflet-control-attribution class used for anything (styling?) for the permalink object?

Best regards,
Jesper

**Comment by brunob** [comment]
Just try to remove the class and you will see that yes this class is useful for the control :p

For your case, you may use a selector that exclude objects that have the two classes.
