### ISSUE TITLE
Can we use Leaflet with paid version of Yandex.Maps API ?

### ISSUE THREAD

**Issue by rudevich** [shramov/leaflet-plugins#161]
Does this plugin really uses Yandex API for getting tiles?
Because they can't sell tiles from big part of world, and in their API there is a limitation for getting them.

**Comment by brunob** [comment]
> Does this plugin really uses Yandex API for getting tiles?

Yes it does : https://github.com/shramov/leaflet-plugins/blob/master/layer/tile/Yandex.js#L125

**Comment by rudevich** [comment]
Thanks :)
