### ISSUE TITLE
Google.js plugin no longer works with leaflet master branch

### ISSUE THREAD

**Issue by bfishman** [shramov/leaflet-plugins#162]
Layers now must extend from L.Layer. As a result, the Google.js plugin no longer works with the Leaflet .80 dev version (master). Do you plan to update this plugin?

**Comment by brunob** [comment]
As i said in #112 i'll wait as soon as leaflet 0.8 will be released...

**Comment by Eschon** [comment]
Maybe it would be a good idea to make a branch for leaflet 0.8 compatibility. So that users who decide to use 0.8 despite the fact that it is not finished yet can still use your plugin.

**Comment by brunob** [comment]
Maybe, but i'm really not hurried about this since #112 was opened a year ago and Leaflet 0.8 is still not released today :p

**Comment by bfishman** [comment]
I understand. Had to switch to .8 recently to use the leaflet.ems plugin. Honeslty considering abandoning leaflet until it's released.
