### ISSUE TITLE
leaflet KML ignores xunits and yunits

### ISSUE THREAD

**Issue by kalenkov** [shramov/leaflet-plugins#163]
leaflet KML ignores xunits and yunits if they defined in pixels. Please look at the simple example below

http://katrine.lpi.ru/kalenkov/leaflet/hotspot-kml.html
http://katrine.lpi.ru/kalenkov/leaflet/hotspot.kml

I expect that the placemark icons should be shifted by 100 pixels in x and 100 pixels in y directions, But instead they completely overlap.

**Comment by brunob** [comment]
Work is on in #163, i think you can close this issue and put your comment there.
