### ISSUE TITLE
Проблема с маркерами на яндекс карте. 

### ISSUE THREAD

**Issue by er24scorpion** [shramov/leaflet-plugins#172]
Когда зумлю, все иконки будто расползаются/сползаются. На osm и google такого нет.

**Comment by brunob** [comment]
hi @er24scorpion sorry but i can only read french, english or spanish :\

**Comment by er24scorpion** [comment]
Sorry. 
When I do something zoom, then my markers spread out in different directions. And polylines too.

**Comment by brunob** [comment]
Hard to help without a link to your page or a jsfiddle...

**Comment by er24scorpion** [comment]
http://jsfiddle.net/0bd5g1gc/1/ 
Bug when I zoom and drag map on Yandex tile.

**Comment by brunob** [comment]
Ok i see, this bug is a duplicate of #111 since yandex tiles are implemented like google tiles...

As i said in this comment https://github.com/shramov/leaflet-plugins/issues/97#issuecomment-114226868 : 

> This script may need a refactoring but i don't plan to do it, feel free to provide pull requests for it :)

**Comment by johnd0e** [comment]
Duplicate of #129
