### ISSUE TITLE
Bing Maps example not working

### ISSUE THREAD

**Issue by mantesat** [shramov/leaflet-plugins#179]
Seems that the Bing maps example is not working any more.

**Comment by brunob** [comment]
Yes, the test key used in the file seems to be outdated : 

http://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial?include=ImageryProviders&jsonp=_bing_metadata_22&key=Anqm0F_JjIZvT0P3abS6KONpaBaKuTnITRrnYuiJCE0WOhH6ZbE4DzeT6brvKVR5&UriScheme=http

I'll try to make a new one asap.
