### ISSUE TITLE
Points of KML not in place

### ISSUE THREAD

**Issue by mariobalca** [shramov/leaflet-plugins#182]
![screenshot from 2015-08-14 16 26 42](https://cloud.githubusercontent.com/assets/4289045/9277336/4a2e6980-42a1-11e5-825a-1afd7dd08ba2.png)

I'm testing the KML layer plugin, everythings looks great but the points of my KML are not on the correct places.

Can you guys help me figure out what's wrong?

**Comment by brunob** [comment]
Your kml should mention hotspot tags for you placemarks.

**Comment by mariobalca** [comment]
But with other KML plugins the points are place just fine, isn't this an issue of the plugin?

**Comment by brunob** [comment]
Which other KML plugin are you using ?

**Comment by mariobalca** [comment]
I've tried the Leaflet.FileLayer, but I didn't like it very much, I'd rather use this one

**Comment by brunob** [comment]
This plugin use togeojson like leaflet omnivore which works great, but doesn't handle kml icons and other kml elements you can use with the KML script in this repo.

You have to set your icons hotspot in your KML file if you want it to display well, without this info, the script can't determine automagically where to put the icon.

Could you post a link to your KML file ?

**Comment by TitanicBush** [comment]
This might be related to the behavior that I describe in #191 .

**Comment by brunob** [comment]
@mariobalca any news about this ? Can we close the issue ?

**Comment by mariobalca** [comment]
I'm sorry, yes you can. I had to remove the points from the KML because I ended up storing them on my db so yeah, you can close this issue

**Comment by brunob** [comment]
No problem, thx for the feedback :)
