### ISSUE TITLE
addLayer fails with Leaflet Beta 1

### ISSUE THREAD

**Issue by af7** [shramov/leaflet-plugins#188]
Hi, I tried to use the google plugin with Leaflet Beta 1 and I get an error on this (leaflet's) code when performing the ``map.addLayer(ggl);`` action:

"Cannot read property 'call' of undefined"

````
L.Map.include({
	addLayer: function (layer) {
		var id = L.stamp(layer);
		if (this._layers[id]) { return layer; }
		this._layers[id] = layer;

		layer._mapToAdd = this;

		if (layer.beforeAdd) {
			layer.beforeAdd(this);
		}

		this.whenReady(layer._layerAdd, layer);   //  HERE IS THE PROBLEM, 'layer._layerAdd' is undefined and the "wenReady" call fails.

		return this;
	},
````

Can this be fixed for BETA 1? I understand that there is no _layerAdd method on the google layer because leaflet 1 made some changes.

Thanks!

**Comment by brunob** [comment]
See #175

**Comment by af7** [comment]
Thank you.

**Comment by brunob** [comment]
You're welcome :)

**Comment by af7** [comment]
I tested this and I observe that when I have the Chrome console (debugger) open there is a noticeable delay on the Google layers moving when dragging the map. Do you see the same? 

This does not happen with the OSM layers. I use a lot of markers drawn with DivIcons that use SVG by the way.

Without the console no delay is noticeable, so it should be OK, but I am just wondering.

**Comment by brunob** [comment]
This is a known bug see #111
