### ISSUE TITLE
Google : setView without zoom makes an infinite loop

### ISSUE THREAD

**Issue by raphael-boucher** [shramov/leaflet-plugins#189]
The zoom option is optional in leaflet doc, but when doing `setView([0, 0])` just after the map creation, leaflet google goes in an infinite loop. It works fine when doing `setView([0, 0], 12)`, for instance.

It looks like leaflet has no zoom value until a layer is added and leaflet google tries to set a zoom value forever in `_checkZoomLevels`.

**Comment by brunob** [comment]
If you look at leaflet source, you'll see that in the beginning of setView : ```zoom = zoom === undefined ? this._zoom : this._limitZoom(zoom);```. I'm not sure you can use this method on load without specifying zoom...
