### ISSUE TITLE
Why is Marker.Rotate.js translating twice? 

### ISSUE THREAD

**Issue by ryanjadhav** [shramov/leaflet-plugins#196]
Trying to investigate a bug where my marker is being displaced from where i want it to be placed. 

What is the purpose of https://github.com/shramov/leaflet-plugins/blob/master/layer/Marker.Rotate.js#L13 && https://github.com/shramov/leaflet-plugins/blob/master/layer/Marker.Rotate.js#L15. Removing these two lines fixes my issue.

**Comment by brunob** [comment]
This is for make marker rotate around bottom/center of its image, if i remove theses lines marker rotate aroud its "center". Maybe your marker use a different offset than leaflet default one (but i think the script handle this case too, to be confirmed) ?

**Comment by ryanjadhav** [comment]
Yes, ideally I want the marker to rotate around the center, would it be possible to make this an option?

**Comment by brunob** [comment]
Jsut tested and it works well if you define iconSize + iconAnchor for your personnal marker icon.
``` javascript
var marker = new L.Marker(map.getCenter(), {
	iconAngle: 90,
	icon: L.icon({
		iconUrl: '../css/cross.png',
		iconSize: [16,16],
		iconAnchor: [8,8]
	})
});
```
