### ISSUE TITLE
Using DeferredLayer along with MarkerClusterGroup plugin issue

### ISSUE THREAD

**Issue by wsenjer** [shramov/leaflet-plugins#200]
Hi, 
I am trying to use Deferred Layer plugin along with MarkerClusterGroup plugin. 
https://github.com/Leaflet/Leaflet.markercluster

I made a jsfiddle case to illustrate the issue, you can check it here.
http://jsfiddle.net/wSytj/156/

The problem is that I get this error message in the console.
`Uncaught Map has no maxZoom specified`

This error is thrown by the Clustering plugin when it is trying to get the MaxZoom of the map. I guess it is thrown because Google API will be not fully loaded yet.
Here is the code where the problem occurs.

```
if (!isFinite(this._map.getMaxZoom())) {
	throw "Map has no maxZoom specified";
}
```
You can check it in their repository here: https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L495

I wonder if you ever used the Deferred loading with Clustering, or may I missed something in my code. 
I will be very grateful if you take a look at this issue.

**Comment by brunob** [comment]
Sorry but i've never used deferred script :\ Since clusterer plugin needs a maxzoom, adding at least one layer without deferrer should fix the bug.

**Comment by wsenjer** [comment]
Adding a default maxZoom to the map itself solved the issue, thank you :)

**Comment by brunob** [comment]
you're welcome :)
