### ISSUE TITLE
Leaflet 1.0 Compatibility

### ISSUE THREAD

**Issue by smitchell** [shramov/leaflet-plugins#201]
Have you begun testing with Leaflet 1.0 beta 2?

**Comment by brunob** [comment]
You may missed #175 :)

**Comment by smitchell** [comment]
Perhaps my problem was Bing? I'll remove references to the Bing plugin on all of my pages and then try the Beta again. I was testing both Bing and Google, http://exploringspatial.com/#demo/4, because we need to support both at work. Thanks for the quick response.

**Comment by smitchell** [comment]
Do you have a CDN version of Google.js available via HTTPS? I recreated the issue on JSFiddle, but I need to source the plugin.

https://jsfiddle.net/stevecmitchell/zmf64m7f/

**Comment by brunob** [comment]
All The scripts in this repo are not yet available on a CDN, but they will soon see cdnjs/cdnjs#6137

Anyway, the script i pointed in #175 will be available when leaflet 1.0 stable will be released. For now, you can embed a copy of #175 patched scripts.

**Comment by smitchell** [comment]
Looking further, I still have the bug with Leaflet 1.0 beta 2. Adding the Google layer to the map causes "callback is undefined" at line 2382 of leaflet-src.js.

I created the error three different ways at JSFiddle (https://jsfiddle.net/stevecmitchell/zmf64m7f/):

1) pass google layer in 'layers' property of L.map() constructor.
2) add the google layer to the map using googleLayer.addTo(map).
3) Choose Google from the layer selector once the map has loaded.

Method 3 is what you'll have to use to get the error on my JSFiddle page at the moment.

**Comment by smitchell** [comment]
Sorry, it took me awhile to realize I was using the unpatched code. I'll try the patched version tonight. Again, sorry for the confusion.
