### ISSUE TITLE
Bing Layers Fails Silently

### ISSUE THREAD

**Issue by arahansen** [shramov/leaflet-plugins#203]
I've found that if using an invalid key for Bing Layers, L.BingLayer will fail silently. 

Perhaps the constructor should throw an error if Bing metadata returns with "InvalidCredentials".

I'd be happy to submit a PR if this is something people would be interested in.

**Comment by smitchell** [comment]
Good suggestion.

**Comment by brunob** [comment]
@arahansen nice, feel free to provide a PR for that :)

**Comment by brunob** [comment]
@arahansen any news about your patch ?

**Comment by brunob** [comment]
Merged & published version 1.5.3, thx :)
