### ISSUE TITLE
Google BicyclingLayer

### ISSUE THREAD

**Issue by smitchell** [shramov/leaflet-plugins#204]
Do you have a way to support the Google Bicycling Layer? https://developers.google.com/maps/documentation/javascript/examples/layer-bicycling

If not is there a way to get a handle to the google.maps.Map from Google.js in order to do this?

``` javascript
  var bikeLayer = new google.maps.BicyclingLayer();
  bikeLayer.setMap(map);
```

The map that I am hoping to replace with Leaflet allows the user to toggle the Bicycle Layer on and off. When a runner is drawing a route she might want to toggle trails on in order to get directions that route over a running/biking trail. Other users might feel that the Bicycle Layer clutters the map opt to turn it off.

I tried to find _google at run time in order to add the bike layer myself, but I didn't find it in the debugger.

Note, we also use the same option for Bing maps (although their trail networks is much less extensive).

**Comment by brunob** [comment]
Sorry but i don't know, i'm putting the minimum effort on google script since it's quite buggy and we still doesn't know if it's really compliant with google tos.  Anyway, feel free to provide a PR for that :)

**Comment by smitchell** [comment]
Okay, I submitted an inquiry to our contracts person yesterday. If I get the green light I will be happy to contribute anyway that I can.

**Comment by rcknr** [comment]
@brunob I'm currently working with Google Maps plugin as well. Just wanted to clarify the ToS thing. [Section 10.1a of Google Maps ToS](https://developers.google.com/maps/terms#section_10) states:

> You will not access the Maps API(s) or the Content except through the Service. For example, you must not access map tiles or imagery through interfaces or channels (including undocumented Google interfaces) other than the Maps API(s).

Which translates to "it's okay when you use it over API". Because in the plugin you actually use the API to display the layer, it complies with ToS. If wouldn't have been okay to add the layer using `L.tileLayer` and tile URLs.

**Comment by brunob** [comment]
@rcknr thx for the feedback, feel free to post your comment on #48 :)

**Comment by rcknr** [comment]
@brunob yeah, just saw there're bigger discussion.

**Comment by rcknr** [comment]
@smitchell You can add bicycling layer like this:

    var googleLayer = new L.Google('ROADMAP');
    map.addLayer(googleLayer);

    var bikeLayer = new google.maps.BicyclingLayer();
    bikeLayer.setMap(googleLayer._google);

**Comment by brunob** [comment]
@rcknr thx for helping @smitchell can we close this issue now ?

**Comment by brunob** [comment]
We can finally close this one since #250 :)
