### ISSUE TITLE
Tileload event for Yandex layers

### ISSUE THREAD

**Issue by rendrom** [shramov/leaflet-plugins#205]
It is possible to imitate Leaflet "tileload" event for Yandex layers?

**Comment by brunob** [comment]
Just removed google mention since #250

**Comment by johnd0e** [comment]
L.Yandex does not operate by tiles (it's solid canvas), so 'tileload' is not applicable to it.
The issue should be closed.

**Comment by brunob** [comment]
Nice, closing :)
