### ISSUE TITLE
Google Plugin does not work with Leaflet 1 flyTo animation 

### ISSUE THREAD

**Issue by thatgirlcancode** [shramov/leaflet-plugins#206]
If you select OSM or Mapbox as the baselayer, flyTo works. If a Google baselayer is selected, the flyTo animation does not work. No errors are thrown. Is there a new event we need to tap into? 

My plunk > http://plnkr.co/edit/ouynceGB0XvjWk7TkWoh?p=preview

**Comment by brunob** [comment]
Have you tried #175 patch before posting ?

**Comment by spikeynick** [comment]
patch #175 does not fix the issues with flyTo

**Comment by brunob** [comment]
Updated copy of #175 patch should fix the bug.
