### ISSUE TITLE
"terms of use" link added by Google are not clickable

### ISSUE THREAD

**Issue by wsenjer** [shramov/leaflet-plugins#211]
Hello,
If you create a map with Google as a basemap, you will notice that the `terms of service` and `feedback` links added by Google on the bottom left corner are not clickable by defaults. Are there any way to make these texts clickable. I guess Google was intending that they are clickable since they are an information reference. Here is an example http://jsfiddle.net/umwo0rn1/76/

Please advise.

**Comment by brunob** [comment]
Hi, the bug seems fixed with leaflet master and #175 patch, you may have a look at this.

**Comment by wsenjer** [comment]
Thanks for the info brunob! looking forward to leaflet v1.0. BTW: I also found a workaround to make the ToS links clickable by adding "pointer-events:none;" to .leaflet-overlay-pane - anyway I am not sure if this has any sideffects, so I will better wait for leaflet v1.0 and the related fixed available with the Google plugin.
