### ISSUE TITLE
Can't get this to work in any browser other than FF

### ISSUE THREAD

**Issue by verticalhorizons** [shramov/leaflet-plugins#220]
Creating a map to run from the computer. Base map is pulled in from the web with pins overlaid from KML files located in the same folder.

This works perfectly on my computer in firefox but in Chrome, Ie and Safari it does not. The base map loads but 'fit bounds' does not occur and the pins are not displayed. Any ideas?

***edit to add, i can't paste the code, the "insert" code button above does not seem to work?!**

**Comment by brunob** [comment]
Could you provide a jsfiddle in order i help you ?

**Comment by verticalhorizons** [comment]
Thanks for your reply Brunob.  I am not having much luck getting jsfiddle to work. It doesnt like the way I am calling external files.  The js should be visible though.

https://jsfiddle.net/qvzfmgbf/

**Comment by brunob** [comment]
Maybe you can provide an online version of your problematic file ?

**Comment by verticalhorizons** [comment]
I had been running this on my computer from a folder on the desktop. I have now uploaded it online to show you and it seems to be working fine when viewed with different browsers. Any idea why chrome/IE/safari don't like the files when they are hosted on the computer?

http://pixelcriminal.co.uk/map/eyts.html

**Comment by brunob** [comment]
These browser doesn't like to play with ajax load on local files, that was your bug, you have to use a local server or simply dev with firefox ;)
