### ISSUE TITLE
Resolve local links

### ISSUE THREAD

**Issue by Arsakes** [shramov/leaflet-plugins#223]
If you put in local paths in href's in kml file, the library cannot read them proprley since it treats all urls the same way (as absolute paths/urls).

I.e if i put my doc.kml file in
`/data_files/doc.kml` 
and `doc.kml` has field `<href>a.png</href>` field the library will try to load.
`/a.png` instead `/data_files/a.png`

**Comment by brunob** [comment]
Yes, it's a browser limitation see #44 ;)

**Comment by Arsakes** [comment]
Well I've "fixed it".
I simply modified to KML.js file to replace local paths (and only them) with base url of doc.kml + relative name.

It works.

**Comment by brunob** [comment]
@Arsakes nice, maybe you can provide a pull request if you think your patch would be useful to others users ?

**Comment by Arsakes** [comment]
Yea, I could - but I think I need to dig deeper into it.
It works - but now I'm not sure if this is really the way it supposed to work :)
