### ISSUE TITLE
Compatibilty with leaflet 1.0.0?

### ISSUE THREAD

**Issue by dirk2014** [shramov/leaflet-plugins#224]
Your leaflet-plugins are running proper with leaflet 0.7.7

If I update leaflet to 1.0.0-rc1, there is a bug in context with leavelet-plugins:
* OSM is running proper
* Google returns the error prompt: Uncaught TypeError: Cannot read property 'call' of undefined

The error is repeatable with leaflet-plugins 1.6.1 and former versions.

Do someone know, how to solve the bug?

You can test it with 
* https://github.com/shramov/leaflet-plugins/blob/master/examples/google.html

You have to move leaflet/v0.7.7 to leaflet/v1.0.0-rc.1

Kind regards
Dirk

**Comment by brunob** [comment]
You may have missed #175 :p
