### ISSUE TITLE
Leaflet API with google tiles and google authentication

### ISSUE THREAD

**Issue by denisandrade** [shramov/leaflet-plugins#227]
Hey guys,

I developed an application using Leaflet API and google tiles.
Following the example https://github.com/shramov/leaflet-plugins/blob/master/examples/google.html

LocalHost the application works correctly.
To deploy the application to production, I need to reference the client id google bought.

But when I refer to my client ID in the link Google Maps, the map does not redenriza the application.
I reference this way: https://maps.googleapis.com/maps/api/js?v=3&libraries=places&client=MyClientID

The following error appears: UnauthorizedURLForClientIdMapError

But I already signed up the URL of my application to be allowed to use the Google Maps service with my client ID.

My question is if this error is occurring because of using this plugin and informing my client ID in reference to Google Maps? 

The google maps not authorize use this plugin ?

Thanks!

**Comment by brunob** [comment]
Hi, sorry but i'm not a google specialist since i don't use their service. Maybe someone here will be able to help you, or you may ask directly to google support.

**Comment by denisandrade** [comment]
Thank brunob,
Initially I suspected that the problem could be a conflict between the plugin and Google use permit, but really the problem was that Google had not authorized the use of the url of my application

**Comment by brunob** [comment]
Ok, we can close this one :)
