### ISSUE TITLE
Delay in the movement of tiles

### ISSUE THREAD

**Issue by denisandrade** [shramov/leaflet-plugins#228]
Hey, guys,

I developed an application using this plugin to be able to use Leaflet api and google tiles

The application works perfectly,

The only problem is when moving the map, the markers plotted on the map move before of the google tiles.
 
Thus the google tiles are with delay in relation to the movement of the markers on the map.
 
I believe this is a consequence of using api leaflet with tiles google.
 
Is there any solution to this problem?
 
Thank you

**Comment by brunob** [comment]
Sorry but nobody have found a solution for this known bug, see #111. I don't plan to work on google layer script, since it use a proprietary service + we still don't really if this is ok with their TOS...
