### ISSUE TITLE
Attribution can disappear when map getBounds( ) return out range values

### ISSUE THREAD

**Issue by sinaru** [shramov/leaflet-plugins#229]
* Browser and version: 
Firefox 47

* Version of Leaflet (`L.version`):  
0.7.2

Steps to reproduce the error:
1. Go to near meridian
2. Be in a zoom level that is around 16
3. Scroll left

What happens is since `map.getBounds()` can return an out of range longitude value from leaflet behavior as noted in [https://github.com/Leaflet/Leaflet/issues/1885](https://github.com/Leaflet/Leaflet/issues/1885), the attribution value will be set as empty on these occasions. 

Check the method definision [`_update_attribution`](https://github.com/shramov/leaflet-plugins/blob/master/layer/tile/Bing.js#L94) and how `getBounds( )` is used.

I was expecting to use `wrap( )` method inside `_updateMapAttribution` so that the bound ranges will be in a valid range.  
PS: Take a look at how [eaflet-bing-layer](https://github.com/gmaclennan/leaflet-bing-layer/blob/gh-pages/leaflet-bing-layer.js#L207) do this.

**Comment by sinaru** [comment]
Thanks. Works as expected.

**Comment by brunob** [comment]
Thx for the feedback, version 1.7.0 published.
