### ISSUE TITLE
Supported leaflet versions

### ISSUE THREAD

**Issue by jekuno** [shramov/leaflet-plugins#232]
Having a look at your `leaflet_one` branch it seems as if you already support leaflet 1.0.
IMHO it might be a good idea if you would add a note to the README which leaflet versions are supported by `leaflet-plugins` currently.

**Comment by brunob** [comment]
Feel free to propose a pull request for that :)

**Comment by jekuno** [comment]
All right, I can do so. ;) Does the master version work with both leaflet 0.7.x and 1.0.x?

**Comment by brunob** [comment]
No, master is for leaflet stable & branch 1.0 for eponym leaflet branch.

**Comment by jekuno** [comment]
Here we go.... one PR for each branch.

**Comment by brunob** [comment]
Thx for that :)

**Comment by jekuno** [comment]
Thx for YOUR work :)
