### ISSUE TITLE
add link-handling to GPX

### ISSUE THREAD

**Issue by hna61** [shramov/leaflet-plugins#235]
The gpx/wpt element has a possible link subelement, which may contain a link to further information.

* http://www.topografix.com/GPX/1/1/#type_wptType
* http://www.topografix.com/GPX/1/1/#type_linkType

The simpliest form of the elemt seems "`<link href='http://some.uri/" />`"

If the link-element exists, the href content should be placed as link (with multi-language-text '[...]') to the end of the popup description of the generated marker.

Example: the following tag
```
<wpt> ...
   <link href="http://more.info/" />
</wpt>
```
should generate the following at the end of the markups popup text:
`<p><a href="http//more.info/" target="_blank">[...]</a></p>`

I will suppose a patch for that, soon.    ...    see PR #236

**Comment by brunob** [comment]
Fixed by #236
