### ISSUE TITLE
Unable to adjust layer opacity

### ISSUE THREAD

**Issue by f00dl3** [shramov/leaflet-plugins#240]
I am unable to adjust a KML layer opacity, using GIF images as the KML data source.

`var radar = new L.KML("Maps/Overlay/RadarB.kml", {async: true, setOpacity: 0.5});`

does not work,  neither does `opacity: 0.5});`

I tried applying `radar.opacity(0.5);` or `radar.setOpacity(0.5);` after AND before `radar.on("loaded"...` as well. Any addition of that property completely hides the KML layer.

**Comment by brunob** [comment]
Please, provide a fiddle or a demo page showing the problem in order to allow us to help you...

**Comment by f00dl3** [comment]
I tried. Not sure what I'm doing wrong but even without demonstrating the bug it's not working... {"error": "Please use POST request"} -- I have no forms in my script at all. 

Either way ... https://jsfiddle.net/yvga3m4d/

**Comment by brunob** [comment]
Your fiddle doesn't include leaflet and the kml script, it would be hard to work in this state...

Anyway, there is no `setOpacity` or `opacity` option for the kml, you have to define opacity of your items in the styles directly in your kml document.
