### ISSUE TITLE
With correct Google Maps loading bug when the app is offline and then go online with the Ionic platform

### ISSUE THREAD

**Issue by ivanssa** [shramov/leaflet-plugins#245]
The vast majority of Google Maps integration implementations with ionic start with the inclusion of the script called `<script src = 'https://maps.googleapis.com/maps/api/js?key=API_KEY&sensor=true'> < / script>` in the index.html

The problem is that I am having a big problem when someone opens your application while offline, then wander cellular or Wi-Fi range and is online again? Your maps will stop working even if they are now online, since the Maps API could not be loaded when the application has been opened!

The right thing to do is load the Google Maps API when you are online, not using a <script> tag and load the asynchronous fashion map,
so I would know how to implement charging for the Google Maps plugin via javascript?

**Comment by brunob** [comment]
Your message seems truncated... what is the exact bug/problem ?

**Comment by ivanssa** [comment]
Hi sorry, I'm using google translator, then you need to use the maps goolge plugin on an ionic app, but as it carries the api via a link script in the index sometimes the app is no map when the app opens in offline and even if aa internet is active the map does not reloads, so I need to fix this bug, it is to find a way to load the api google maps of ascrona way without nescessidade to connect to an external server google to request api.

**Comment by ivanssa** [comment]
Hello I have been traveling net to net for months in search of a solution to this serious problem and I found this post that reports the same problem and a possible solution someone could this solution to load the google maps api if form donamica asynchronous only when the user has Internet in this google plugin? Http: //www.joshmorony.com/part-3-advanced-google-maps-integration-with-ionic-and-remote-data/

**Comment by brunob** [comment]
Google layer are not handled in this repo anymore, see #250 :)

**Comment by ivanssa** [comment]
Hello Brunob thanks for the answer however the suggestion does not solve the problem, the script that indicated also depends on the inline inclusion of google api generating the same error, as the leaflet plugin to include google maps other than OpenStreetMap it depends on the inclusion of api Through an entry in the index.html <script src = "https://maps.googleapis.com/maps/api/> If the user accesses the app without internet it tries to call the api and the 404 occurs from this moment memso That it connect to the internet the map will not work until close and reopen the application, so the state of loading the script depends on a routine to load the api dynamically so the error is not in google api and so it is rather a pertinent question For the script to handle this bug, I hope someone can help me in a solution to make this plugin work even if the user activates the network after they open the app.
