### ISSUE TITLE
Layer Google Map not work on IE11

### ISSUE THREAD

**Issue by auban** [shramov/leaflet-plugins#247]
Hello,

The layer google map not work on IE11 after the version 1.9.1
On IE the Promise is not supported.

Best regards,

Auban

**Comment by brunob** [comment]
ping @nmccready this one is for you ;)

**Comment by nmccready** [comment]
If there is no promise then you need to ship the promise dependency in.

**Comment by nmccready** [comment]
Shim

**Comment by joggienl** [comment]
Hi,

I saw the "Promise" is being used since 1.9.1. In 1.9.0 it "worked" in IE. Promises are known not to work in IE (see here for reference: http://caniuse.com/#search=Promise).

Why introducing such a breaking change in a patch version? I've got a build process which automatically installs this plugin via package manager. I thought I could safely use version "~1.9.0". Following the semantic versioning, I would expect not to have this kind of breaking changes. Quite disappointed about this actually. If I would want to update to 2.x (or 1.10.x if that was on the roadmap) then I should be prepared to have breaking changes. Not for patches.

Any idea's on how to fix this without the need of an extra shim? Can you patch with a version that works also in IE, as expected?

Thanks in advance!

**Comment by nmccready** [comment]
I can't look at this right now as I am on vacation. As for the version number, it was not my decision as I am not the owner of the repo. If anything I should have advised that it was breaking. However this is obvious in the original PR. 

As far as Promises go, I think you should shim as it is 2016 and Promises should be standard.

**Comment by joggienl** [comment]
Thanks for your quick response! Much appreciated! While you're on vacation, you're obvious not required to respond (that quickly).

I can agree with that it is 2016 (fact) but the other fact is that IE does not support them and we have little to no influence on that. Shims are "fine" to make it happen on IE but perhaps it would be nice if the shim was shipped (backwards compatibility). That't the whole point in semver as I see it: no breaking changes in patches..

Besides looking to the changes itself I could not find actual information about this breaking change? Or did I misread something?

For now I will solve this to point to 1.9.0 directly. Still hope that this will be fixed anytime soon!

Thanks again!

**Comment by nmccready** [comment]
When I I get back I can try to make it backwards compatible.

**Comment by joggienl** [comment]
Thanks! Enjoy!

**Comment by brunob** [comment]
> As for the version number, it was not my decision as I am not the owner of the repo.

My bad, i should have bump a major version if i only knew the chage was so big...

> If anything I should have advised that it was breaking. 

Nice to read this

> However this is obvious in the original PR. 

Not so obvious, anyway it's surely my fault to be confident about what people propose on this repo, and thanks for taking care of this bug @nmccready :)

**Comment by nmccready** [comment]
After thinking about diving into this code and directly shimming it into this codebase, I find it still unnecessary. As do other libraries like [fetch](https://github.com/github/fetch/issues/114). 

We should not be adding unnecessary bloat for those that need to support legacy browsers. I think it is unreasonable to make the users at mass support IE11.

If @brunob absolutely wants it to be backwards compatible then we might as well rip out promises and redo it in callbacks. 

Again, I am in favor of pushing forward with ES6 type features that should be in the browser or shimmed already.

**Comment by joggienl** [comment]
Hi @nmccready, It's not about the feature itself. It's a good thing to develop and push new things. It's about breaking stuff that should not have been broken. That's why we use versioning and especially semantic versioning. The summary on top of http://semver.org/ is pretty clear about it.

**Comment by joggienl** [comment]
More specifically about the issue itself, it would be perfectly fine to introduce Promisses in a new major version and making a reference to a shim library for those who need IE support.

**Comment by nmccready** [comment]
Thing is the version major number has been bumped. So is it worth thr effort to fix the screw up for being "right".

**Comment by joggienl** [comment]
I would say yes to that question.. people who rely on this version could get reports for their site or app not working anymore (just like I did).

I haven't looked at the exact functionality that has been added.. maybe it's an idea to revert the functionality that brings the Promise to play and than bump that as 1.9.3?

**Comment by nmccready** [comment]
I'll just revert to use callbacks if possible for 1.9.3. The main influence for my PR was because the google layer was not loading on mobile. 

Again I can't make merges and only make a PR like everyone else.

**Comment by brunob** [comment]
This seems the right solution, now **we** got to find out the best way to handle this mess up : 

Should we publish 1.9.3 to a separate branch or revert on master ? Maybe we should add a warning about this ine the README too.

Anyway, PR are always welcome...

**Comment by joggienl** [comment]
Just made a PR. Take a look on #248. Hopefully this will help!

**Comment by joggienl** [comment]
#248 has been merged into v1 branch.
#249 should be te last be really fix the breaking changes made.

**Comment by brunob** [comment]
@joggienl merged, thx for that.

**Comment by joggienl** [comment]
Thanks! Appreciate that you merged them in!
As a final thing... Can you also publish them to npm / bower?

**Comment by brunob** [comment]
Done

**Comment by brunob** [comment]
No news ? Closing this one...
