### ISSUE TITLE
leaflet.js:6 Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by intersel** [shramov/leaflet-plugins#252]
When trying to run the example/google-custom.html with the version 1.0.1 of leaflet (http://cdn.leafletjs.com/leaflet/v1.0.1/leaflet.js), I've got this error
leaflet.js:6 Uncaught TypeError: Cannot read property 'call' of undefined

Does it mean that the plugin is not compliant with version > 0.7.7 ?

**Comment by tomhuze** [comment]
Having same issue

**Comment by brunob** [comment]
Have you searched in issues ? See #250 & #175 & others, tl/dr google script is not compatible with leaflet 1.0 :)
