### ISSUE TITLE
Yandex tiles mooving speed differs from overlays mooving speed

### ISSUE THREAD

**Issue by kostjerry** [shramov/leaflet-plugins#253]
Try to drag a map and investigate the marker https://jsfiddle.net/cLpxr3ou/4/

**Comment by brunob** [comment]
Yes, i think the problem is the same that we get in old google script, maybe someone should make a new yandex script based on new google script made by @IvanSanchez see #250

**Comment by IvanSanchez** [comment]
If this is a problem with more than one provider (Google + Yandex + others?), then it *might* be a good idea to create a generic GridMutant, and then let subclasses like GoogleMutant and YandexMutant specify the mutant initialization and the image regexps. If anybody feels like taking up on this, code is welcome at https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant

**Comment by brunob** [comment]
Thx for the answer @IvanSanchez :) Yandex is the last "thorn in" of this repo and i would be glad to see someone refactor it, @kostjerry i hope you'll take it ;)

**Comment by kostjerry** [comment]
Thanks for the answers!
I'll try.

**Comment by kostjerry** [comment]
Here is my repo with YandexMutant based on GoogleMutant: https://github.com/kostjerry/leaflet-yandex
However, while debugging I noticed that mutant functions are never used, but the bug #253 is fixed.

**Comment by IvanSanchez** [comment]
@kostjerry Yeah, you gotta make sure that the image URLs loaded by yandex match some of the regexps. I expect those to be different from Google.
