### ISSUE TITLE
decodeURIComponent() fails

### ISSUE THREAD

**Issue by NielsHolt** [shramov/leaflet-plugins#254]
Hi
In line 151 of leaflet-plugins/control/Permalink.js 
p[tmp[0]] = decodeURIComponent(tmp[1]);
may fail if the user has entered and incomplete url.
The solution is to use try-catch around decodeURIComponent

**Comment by brunob** [comment]
Feel free to propose a patch in a pull request @NielsHolt

**Comment by brunob** [comment]
Anyway @NielsHolt could you provide a jsfiddle or materials to make a test case ?

**Comment by NielsHolt** [comment]
Hi
It simply that decodeURIComponent fails if the parameter is an incorrect part of a query string. Eg. If an user copies an url and don't get all of it right decodeURIComponent can fail. 
decodeURIComponent("absc%2") will fail

**Comment by NielsHolt** [comment]
All that is needed is to replace line 151
```
p[tmp[0]] = decodeURIComponent(tmp[1]);
```
with
```
try {
    p[tmp[0]] = decodeURIComponent(tmp[1]);
}
catch (e) {
      p[tmp[0]] = tmp[1];
}
```

**Comment by brunob** [comment]
I've tried to reproduce your bug without success, i don't get any error with an incomplete url, a test cas would have be nice... Anyway, i've implemented your patch.

**Comment by NielsHolt** [comment]
Thanks
`var test = decodeURIComponent("absc%2");
`
Gives an error (in Chrome)
