### ISSUE TITLE
bower.json in release 3.0.0 incorrect

### ISSUE THREAD

**Issue by NielsHolt** [shramov/leaflet-plugins#255]
Hi
In release 3.0.0 the file control/distance.js is listed under main, but the file do not exists any more
Could you please update bower.json

**Comment by brunob** [comment]
Maybe have you missed 0d639aad6a2618d2be3527964236c0a24091c540 ?

Or maybe i have ton increment version in order to make the change "available" to bower users ? I don't know anything about bower :p

**Comment by NielsHolt** [comment]
A new release (3.0.1) would make it easy for bower-users to get the right version – Thanks J

**Comment by brunob** [comment]
Is it urgent, does it generate errors for bower users ? I would prefer to publish a new version with "real" code change and not only this :p

**Comment by NielsHolt** [comment]
It is not urgent for me J, but bower fails if you install version 3.0.0 due to the missing file listed in bower.json main
