### ISSUE TITLE
How to rotate in place?

### ISSUE THREAD

**Issue by distante** [shramov/leaflet-plugins#257]
I want to use [Market.Rotate.js](https://github.com/shramov/leaflet-plugins/blob/master/layer/Marker.Rotate.js) to rotate a marker that is basically a circle with an arrow inside and the marker position is in the middle of this circle.

Right now this does not work because it assumes the marker is a pin and I can not find the correct way to make it rotate in place.

How can I accomplish that?

**Comment by brunob** [comment]
Hmm have you set your icon anchor ? Can you provide a fiddle or a demo page ?

**Comment by distante** [comment]
I make a quick fiddle [Here](https://jsfiddle.net/Saninn/3r9s3ncx/), as you can see, when I set the angle to 100 it moves from the map point

**Comment by brunob** [comment]
As i said, set your icon anchor with the right value and u're done :)

https://jsfiddle.net/r4y9awp4/

**Comment by distante** [comment]
Ah, sorry, you where rigth. I left here my updated fiddle because you forgot to put the icon anchor on yours :)
[Updated Fiddle](https://jsfiddle.net/Saninn/r4y9awp4/1/)
