### ISSUE TITLE
Move TileLayers inside "leaflet-tile-pane"

### ISSUE THREAD

**Issue by rendrom** [shramov/leaflet-plugins#261]
What do you think about putting layers containers (such as `leaflet-yandex-layer`) inside the `leaflet-tile-pane` container?

**Comment by brunob** [comment]
It sounds good and since i don't use these tiles i think you're right :p

More on this, think these tiles should be handled like google tile now see #250 & https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant

Anyway, feel free to provide a pull request :)

**Comment by johnd0e** [comment]
#285

**Comment by brunob** [comment]
Can be closed since #285 is merged
