### ISSUE TITLE
Cache the Imagery Metadata (Bing Maps)

### ISSUE THREAD

**Issue by mcartoixa** [shramov/leaflet-plugins#263]
This is a request for a (maybe) special case: we use the Bing Maps provider to create thumbnails for our data in a search engine. The tiles seem to be fetched cleverly, and they are cached in the browser.

My problem is that if I create 20 thumbnails, the Bing provider will fetch the Imagery Metadata 20 times (with the same results, obviously). So the number of [_billable transactions_](https://msdn.microsoft.com/en-us/library/ff859477.aspx) skyrocket needlessly (by a factor of about ~20 in my case) and so do my costs.

Do you think it would be possible for multiple Bing layers to share the same metadata?

**Comment by brunob** [comment]
> Do you think it would be possible for multiple Bing layers to share the same metadata?

I've nether think about this so i have no clue, but feel free to provide a PR if you have a patch for it :)

**Comment by mcartoixa** [comment]
Well, the clock was ticking so I ended up integrating my own version of the plugin in our project. After battling with the asynchronous nature of JSONP requests (I don't know how you manage to make it work,  btw), my plugin is now about twice the size of the original so I don't know if you could call that a patch ;-)

I may open source it at some point.

The principle is quite simple:

- you store the metadata in an object that is global to the module. The metadata depends on the imagery set, the culture and the protocol used (HTTPS).
- if you can't find the right metadata, go fetch it and store it.
- if you are fetching metadata, every layer that is dependent on it waits for the result (I use window.addEventListener for this).

**Comment by brunob** [comment]
Ok, thx for the feedback, i think we can close this issue now you found a way to manage it by your side.
