### ISSUE TITLE
Common questions about relese 3.0

### ISSUE THREAD

**Issue by bopoh13** [shramov/leaflet-plugins#264]
The Leaflet 1.2 is used at the moment, but there are significant differences with the previous release. I propose to discuss the issues below.

**EN:** _GitHub Pages is not installed in the settings of this repository. I had to create a temporary repository for viewing the work of plugins (there are no problems on the local machine) ._

1. Leaflet 1.2 perfectly loads [geojson](http://leafletjs.com/examples/geojson/), but in old mobile browsers for Android does not work (in fact only markers). Are the plugins of this repository built into it?
2. Browsers like FF57 cut mixed content. I propose to change the protocol on HTTPS in all files as
https://github.com/shramov/leaflet-plugins/blob/bd0a4bfa617b27d115001053475da51ca19f99c6/examples/gpx.html#L4-L5 https://github.com/shramov/leaflet-plugins/blob/bd0a4bfa617b27d115001053475da51ca19f99c6/examples/gpx.html#L12 https://github.com/shramov/leaflet-plugins/blob/bd0a4bfa617b27d115001053475da51ca19f99c6/examples/gpx.html#L15-L16
3. Plugins of release 3.0 draw lines through _canvas_ or _svg_? In the [previous release](http://psha.org.ru/leaflet-plugins/examples/) plugins in the old mobile browser for Android are displayed normally (loaded Leaflet 0.7), and in the current there are no lines and no markers.
4. Is this a problem in the Leaflet and can not fix it already?
<hr>

**RU:** _В настройках этого хранилища не установлен GitHub Pages. Мне пришлось создать временное хранилище для просмотра работы расширений (на локальной машине проблем нет)._

1. Leaflet 1.2 прекрасно загружает [geojson](http://leafletjs.com/examples/geojson/), но в старых мобильных браузерах под Android не работает (по факту только маркеры). Павел, в него встроены ваши расширения?
2. Современные браузеры (как FF57) режут смешанный контент. Предлагаю изменить в файлах протокол на HTTPS
https://github.com/shramov/leaflet-plugins/blob/bd0a4bfa617b27d115001053475da51ca19f99c6/examples/gpx.html#L4-L5 https://github.com/shramov/leaflet-plugins/blob/bd0a4bfa617b27d115001053475da51ca19f99c6/examples/gpx.html#L12 https://github.com/shramov/leaflet-plugins/blob/bd0a4bfa617b27d115001053475da51ca19f99c6/examples/gpx.html#L15-L16
3. Ваши расширения выпуска 3.0 рисуют линии через canvas или svg? [В предыдущем выпуске](http://psha.org.ru/leaflet-plugins/examples/) расширения в старом мобильном браузере под Android отображаются нормально (подключён Leaflet 0.7), а в текущем нет ни линий, ни маркеров.
4. Проблема в Leaflet и _как раньше_ не будет никогда?

**Comment by johnd0e** [comment]
> 1\. Leaflet 1.2 perfectly loads [geojson](http://leafletjs.com/examples/geojson/), but in old mobile browsers for Android does not work (in fact only markers). Are the plugins of this repository built into it?

No.


> 2\. Browsers like FF57 cut mixed content. I propose to change the protocol on HTTPS in all files

Good Idea. Could you make PR for this?



> 3\. Plugins of release 3.0 draw lines through _canvas_ or _svg_?

Please specify what exact plugins do you mean, and show sample code that leads to mentioned issues.




> 4\. Is this a problem in the Leaflet and can not fix it already?

It's hard to say without knowing what exact issues do you have.
AFAIK, all the plugins in this repo should work with latest repo. But not sure about ancient Android versions.

**Comment by brunob** [comment]
Point 2 fixed ;)

**Comment by johnd0e** [comment]
> Point 2 fixed ;)

Only in some examples.

BTW, I found that `deferred.html` need to be fixed for current `L.Yandex`. Will make PR.

**Comment by brunob** [comment]
Can we close tis issue now ?

**Comment by johnd0e** [comment]
+
