### ISSUE TITLE
how can i disable the start and end Marker Icon in leaflet Gpx:

### ISSUE THREAD

**Issue by labneu** [shramov/leaflet-plugins#266]
**Help,**
how can i disable the start and end Marker Icon in leaflet Gpx:
please how can I solve this problem
Thanks a lot**
By default gpx.js will use pin-icon-start.png, pin-icon-end.png and pin-shadow.png as the marker icons URLs for, respectively, the start marker, the end marker and their drop shadow. Since it might not be convenient that these images have to reside under the same directory as your HTML page, it is possible to override the marker icon URLs and sizes by passing a marker_options object to the GPX options object.

**Comment by brunob** [comment]
Hi, have a look at https://github.com/shramov/leaflet-plugins/blob/master/examples/gpx-no-wpt.html that doesn't show any icon.

**Comment by labneu** [comment]
Hi Bruno 
Merci pour la réponse, mais ou intégrer le script ??
thanks, but where should the script insert. as include in TS or in Leaflet JS

**Comment by brunob** [comment]
Je ne comprends pas la question. Tu insères le script de prise en charge des GPX dans ta page comem dans l'exemple et zou https://github.com/shramov/leaflet-plugins/blob/master/examples/gpx-no-wpt.html#L6

**Comment by labneu** [comment]
merci , je suis en train d´actualiser mon site avec la version typo3 8.6, sur un Template de mon provider  ou tous les script et les include sont dans une ext. 
PS. je suis un amateur de 72 ans qui programme selon la Methode "learning by doing" 
www.logisandbike.com

**Comment by brunob** [comment]
De rien, mais je pense qu'il vaut mieux que tu vois toutes ces questions avec le provider de ton template ;)
