### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by kmiyashiro** [shramov/leaflet-plugins#27]
What license is this code under? MIT?

**Comment by valerio-bozzolan** [comment]
Please consider using an already existing license. In many part of the world your license is certainly not valid (for example the phrase «All rights reserved» it is incontrast with «Redistribution and use in source and [..] are permitted»).

If you want your name on every fork of your files and you want to take advantages on forks code, please consider the great [GNU General Public License v3](http://www.gnu.org/licenses/gpl-3.0.txt).

If you allow people to create proprietary software with you code (as your current license), use something similar to the [MIT license](http://opensource.org/licenses/MIT) or the [Apache 2.0](http://directory.fsf.org/wiki/License:Apache2.0):

The GNU GPL, the Apache 2 and the MIT license have the same disclaimer, so you are not responsible for every problem. All are practically recognized at worldwide level. All grant that "you" are the copyright holder and your name can't be legally deleted.

**Comment by brunob** [comment]
Hi @valerio-bozzolan as said in the commit log, the license of the repo is the same as Leaflet core which seems to be a BSD license :

https://github.com/Leaflet/Leaflet/blob/master/LICENSE

http://opensource.org/licenses/BSD-2-Clause
