### ISSUE TITLE
Marker text creating new lines after every word/space

### ISSUE THREAD

**Issue by RajibChanda** [shramov/leaflet-plugins#273]
I am using **Marker.Text.js**, but when I am adding a text string in marker it breaks down that string in separate lines after every space. Is there any way to show a limited number of words per line without losing the actual position of the marker/ without offsetting the marker position?
![issue](https://user-images.githubusercontent.com/15677821/41273354-e6315da2-6e3a-11e8-9675-a904dcec6d12.JPG)
@brunob

**Comment by brunob** [comment]
Can you provide a link to a page or a fiddle showing the bug please ?

**Comment by AntoniBCN** [comment]
I've the same problem:
```

var marker = new L.Marker.Text(map.getCenter(), 'LOREM LIPSUM DOLOR');
map.addLayer(marker);
```
Generates:
![textmarker](https://user-images.githubusercontent.com/26866763/41653722-4906d20c-7487-11e8-84a7-8515e038e1bd.jpg)

Any idea?

Thanks in advance

**Comment by RajibChanda** [comment]
@brunob

**Comment by brunob** [comment]
@RajibChanda i've read that, not necessary to ping me, i'll take a look at this asap. Anyway, feel free to send a patch.

**Comment by velocat** [comment]
into Marker.Text.js line 11 add  css rule "nowrap" :)
```
el.style.cssText = "color:blue; font-size:14px; font-weight:bold; white-space:nowrap;";
el.style.textShadow = '2px 2px 2px #fff';
```

**Comment by brunob** [comment]
thx for the hint @velocat ;)
