### ISSUE TITLE
error in example

### ISSUE THREAD

**Issue by astomas** [shramov/leaflet-plugins#283]
I've tried to use the example for permalink but have the following error in console:
"L.Control.Permalink is not a constructor  at permalink.html:27".
l.27 is "map.addControl(new L.Control.Permalink({text: 'Permalink', layers: layers}));"
the .js permalink are correctly referenced (no error finding them in console).
An idea why?
Thanks

**Comment by brunob** [comment]
I can run the example provided in the repo without any error, can't help you without a link to a fiddle showing the bug.
