### ISSUE TITLE
Marker.Text has wrong anchor

### ISSUE THREAD

**Issue by johnd0e** [shramov/leaflet-plugins#286]
![image](https://user-images.githubusercontent.com/1838643/58252198-31fc3e80-7d6e-11e9-8590-c326d065af0a.png)

It's screen from unmodified `marker-text.html`, where we see 2 markers.
I suppose their pins should be placed in exact point.

**Comment by brunob** [comment]
Please, provide a link to a page showing the bug. I'm sorry to tell this, but i can't debug an image, especially without any context about it. All i can say, is : this works for me :)

**Comment by johnd0e** [comment]
https://github.com/shramov/leaflet-plugins/blob/master/examples/marker-text.html

**Comment by brunob** [comment]
Nice, and what about the context, since the same example works for with FF 67 on ubuntu <= this is a bit of context.

_Sorry to be rude, but i feel a bit tired about this type of bug report_

**Comment by brunob** [comment]
'k, thx to me, i see it with chromium, let's dig into it

**Comment by brunob** [comment]
The problem comes from this line https://github.com/shramov/leaflet-plugins/blob/master/layer/Marker.Text.js#L47 it should have been a specific webkit hack not needed anymore.
