### ISSUE TITLE
Yandex map resize works incorrectly

### ISSUE THREAD

**Issue by dark-gray** [shramov/leaflet-plugins#293]
Hi.
Yandex map pane changes its size incorrectly since release 3.1.0 (see gif)
![Size trouble](https://user-images.githubusercontent.com/13743005/62835590-fd0fd180-bc62-11e9-89ed-cdc18007c42e.gif)

As i can see, it's because you removed __resize_ function call from __update_ function (it was there in previous versions).
At least, i solved this problem by returning __resize_ function back.
```
_update: function () {
    this._resize(); // RETURNED THIS

    var map = this._map;
    var center = map.getCenter();
    this._yandex.setCenter([center.lat, center.lng], map.getZoom());
    var offset = L.point(0,0).subtract(L.DomUtil.getPosition(map.getPane('mapPane')));
    L.DomUtil.setPosition(this._container, offset); // move to visible part of pane
},

_resize: function (force) {
    var size = this._map.getSize(), style = this._container.style;
    if (style.width === size.x + 'px' && style.height === size.y + 'px')
        if (force !== true) return;
    this.setElementSize(this._container, size);
    this._yandex.container.fitToViewport();
},
```
And after that:
![Size trouble solved](https://user-images.githubusercontent.com/13743005/62835713-267d2d00-bc64-11e9-9651-95a54f9f764b.gif)

**Comment by brunob** [comment]
Thx for the report, ping @johnd0e ;)

**Comment by johnd0e** [comment]
Hi.

> Yandex map pane changes its size incorrectly since release 3.1.0 (see gif)

I see gif, but I cannot reproduce this with standard example `yandex.html`.
Could you provide your code?

**Comment by johnd0e** [comment]
@dark-gray
@all

Is there someone who can tell me how to reproduce the issue?
I'd like to fix it, in proper way (that code sample above is not good).

**Comment by belazz** [comment]
I've run into the similair issue, resizing the container and then executing `map.invalidateSize();` doesnt update the map/tiles, though objects are getting redrawn:

![Screenshot_11](https://user-images.githubusercontent.com/21983564/95657173-aea7dc80-0b5e-11eb-80c6-55401757b25d.png)


To reproduce the issue:
1. Change the width of the map container dynamically
2. Run `map.invalidateSize();`
3. Updates the map properly for other providers (like OSM, or using yandex maps direcly through L.tileLayer), but doesnt work for L.yandex()

`map.invdalidateSize()` works as expected on 3.0.3

**Comment by johnd0e** [comment]
@belazz 

Could you provide complete sample using some sandbox (like jsfiddle or similar)?
And what if you skip step 2?

**Comment by belazz** [comment]
@johnd0e 
Sorry for not providing jsfiddle right away: https://jsfiddle.net/tsdp7j4r/3/ (1500ms timeout for container resize)

Skipping step 2 doesnt affect L.yandex in any way, but it affects others - they are not getting updated. You can try it in the jsfiddle I provided (try commenting out map.invalidateSize() and see the difference)

**Comment by johnd0e** [comment]
Ok, I see now.
Perhaps we need to reintroduce `_resize` method.
```js
	_resize: function () {
		this._yandex.container.fitToViewport();
	}
```
I will check this later (or feel free to do it yourself).
