### ISSUE TITLE
Yandex maps scaling work incorrectly

### ISSUE THREAD

**Issue by cuurjol** [shramov/leaflet-plugins#294]
Hello.

I opened the example of [Yandex maps](https://github.com/shramov/leaflet-plugins/blob/master/examples/yandex.html) by downloading your repository.

And I noticed that Yandex maps work correctly on Google Chrome browser, but if I change this browser to Mozilla Firefox, Yandex maps work incorrectly. Please solve this issue.

**Comment by brunob** [comment]
Have you checked #293 ?

**Comment by cuurjol** [comment]
Yes I have, but his solution doesn't work. May be for me, I don't know.

**Comment by johnd0e** [comment]
Confirming the issue.
Known workaround: set map options `zoomAnimation` property to `false`.

**Comment by a-a-k** [comment]
@johnd0e your temp solution works, thank you. But is there any solid fix?
![giphy](https://user-images.githubusercontent.com/5455861/66063699-2156a300-e56e-11e9-8b86-10618f76bfe6.gif)

**Comment by johnd0e** [comment]
Sure. It's merged into `master` already.

**Comment by a-a-k** [comment]
@johnd0e but as you can see below it somehow does not work. I'm using right version I hope.
![image](https://user-images.githubusercontent.com/5455861/66126131-e8243e80-e612-11e9-8111-5e1d8bbc5b99.png)

**Comment by johnd0e** [comment]
> I'm using right version I hope.

Nope.
Right version is unreleased.
https://rawcdn.githack.com/shramov/leaflet-plugins/efd0a870496fa55fd51904fff781b6d214e09fa6/layer/tile/Yandex.js

**Comment by brunob** [comment]
I've just released v3.3.1 for that ;)
