### ISSUE TITLE
Yandex SearchControl not works

### ISSUE THREAD

**Issue by a-a-k** [shramov/leaflet-plugins#296]
Firstly, it has a strange position. At what layer it is? How can I drive it's sizing?

![image](https://user-images.githubusercontent.com/5455861/66127181-50741f80-e615-11e9-914f-21c744671b9d.png)

While searching something even only one time I'm always getting the next error

![image](https://user-images.githubusercontent.com/5455861/66127308-86190880-e615-11e9-87ab-f634035209c2.png)

**Comment by johnd0e** [comment]
1. It is working. Just use proper api key.
2. We do not define position of yandex 'native' controls. You can use [ymaps](https://tech.yandex.com/maps/jsapi/doc/2.1/ref/reference/control.SearchControl-docpage/) api for that.
Or it may be possible via css.
