### ISSUE TITLE
yandex hybrid layer didn't work

### ISSUE THREAD

**Issue by hkucuk** [shramov/leaflet-plugins#299]
<img width="1134" alt="Ekran Resmi 2019-11-21 21 38 16" src="https://user-images.githubusercontent.com/4687797/69366424-67df9880-0ca7-11ea-8abd-6c03db361382.png">

Hello, When I chose hybrid layer in the example, map size got smaller and it didn't work properly.

**Comment by johnd0e** [comment]
I am unable to reproduce this issue with examples/yandex.html.
Please specify your browser version, and show your code (preferable using https://jsfiddle.net/ or similar sandbox)

**Comment by hkucuk** [comment]
Hello,
When I checked again the example, i didn't see the issue. Before I restart my computer, I had a lot of opened tab in chrome. Maybe the reason of issue is this. Currently everything works excellent . Thank you for your quick response.
