### ISSUE TITLE
Yandex player map size

### ISSUE THREAD

**Issue by dmis53** [shramov/leaflet-plugins#301]
Why do panoramas look like this on the official Yandex website, the panorama window occupies 80% of the screen, below the map. In the variant with connection to the leaflet, a window with a 300x200px map is created. Maybe there is an option that does this and which I don’t know about?

Yandex:
![image](https://user-images.githubusercontent.com/57702525/70423634-51975200-1a87-11ea-9859-82482db249db.png)

Leaflet:
![image](https://user-images.githubusercontent.com/57702525/70423735-873c3b00-1a87-11ea-8ea2-e57c7bb94b31.png)

**Comment by johnd0e** [comment]
> Maybe there is an option that does this and which I don’t know about?

This plugin is just thin wrapper over rich ymaps api, where you cann see plenty of [options](https://tech.yandex.com/maps/jsapi/doc/2.1/ref/reference/panorama.Player-docpage/).

We are unable to provide support on it (and it'd be really tricky to integrate most of them into leaflet environment).
Though you should try to achieve your goal using ymaps api, and share here your success story, or propose enhancements via PR.

**Comment by brunob** [comment]
Should we close this one ?

**Comment by dmis53** [comment]
I think yes
