### ISSUE TITLE
Changing the Bing Maps Base URL

### ISSUE THREAD

**Issue by JohZed** [shramov/leaflet-plugins#304]
Hi,

I would like to send the requests to Bing maps via a proxy in order to hide the key in my single page application. Is there a way to change the base URL to my proxy server?

**Comment by johnd0e** [comment]
> Is there a way to change the base URL to my proxy server?

There is no straight forward way.
But you may try this this things:
- change `_makeApiUrl` to fit your needs
- then
  - either train your proxy, to return already fixed url template
  - either fix url locally, e.g. you may patch `this._url` in 'load' listener
