### ISSUE TITLE
Google : zoom buttons do not work with LL master as of 02/21/2013

### ISSUE THREAD

**Issue by nhinze** [shramov/leaflet-plugins#62]
Hi,

no sure what is going on, but the Google Maps layer does not work with Leaflet master as of 02/21/2013. It works fine with LL 0.5.1

The zoom buttons do not respond and if you zoom out using pinch zoom it also breaks.

**Comment by robertharm** [comment]
FYI: I could reproduce the issue on desktop with latest firefox, chrome and IE - adding
`L.polyline([[0, 0], ]).addTo(map);`
fixed this issue for me

**Comment by brunob** [comment]
For info Leaflet/Leaflet#2021 seemed to be not totally fixed, there are some new commits for it.

**Comment by nishantkmr** [comment]
Adding L.polyline([[0, 0], ]).addTo(map); fixed the issue.

**Comment by FractalizeR** [comment]
This bug also affects Yandex maps tile on leaflet 0.7.3 and Yandex Tile 7832605ab5bb8f0a759baf3478df7a567affa45d

Adding L.polyline([[0, 0], ]).addTo(map) also fixed the issue.

**Comment by ianpetzer** [comment]
Just to confirm I've experienced the exact same problem as described in https://github.com/shramov/leaflet-plugins/issues/98 (A map with Google Maps layer, { zoomAnimation: true } and single marker freezes on zoom

This is with leaflet 0.7.3 and leaflet-plugins 1.3.6

The polyline workaround seems to remove the problem

**Comment by sebastianjonasson** [comment]
I did however manage to get it working by setting zoomAnimation to false. Leaflet 0.7.3

**Comment by brunob** [comment]
Same as #111, closing this old issue since nobody is working on it. Feel free to provide a pull req for that :)
